# Generated by Django 5.2.1 on 2025-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
